export const FIND_MOVIE = 'FIND_MOVIE';
export const REMOVE_MOVIES = 'REMOVE_MOVIES';
export const GET_SEARCH_STRING = 'GET_SEARCH_STRING';
export const GET_FAVORITES = 'GET_FAVORITES';
export const ADD_FAVORITES = 'ADD_FAVORITES';
export const REMOVE_FAVORITES = 'REMOVE_FAVORITES';
export const GET_TOP_RATED_MOVIES = 'GET_TOP_RATED_MOVIES';
export const GET_POPULAR_MOVIES = 'GET_POPULAR_MOVIES';
